backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

site_url: "https://ml-testnetlify.netlify.app/"

media_folder: "assets/uploads"      # où stocker les images uploadées
public_folder: "/assets/uploads"

collections:
  - name: "clients"
    label: "Clients"
    folder: "_clients/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Age", name: "age", widget: "number" }
      - { label: "Job", name: "job", widget: "string" }
  # - name: "products"
  #   label: "Produits"
  #   folder: "data/_products/"
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - { label: "Nom", name: "name", widget: "string" }
  #     - { label: "Description", name: "description", widget: "text" }
  #     - { label: "Prix", name: "price", widget: "number" }
  #     - { label: "Catégorie", name: "category", widget: "select", options: ["furniture", "lighting"] }
  #     - { label: "Tags", name: "tags", widget: "list" }
  #     - { label: "Dimensions", name: "dimensions", widget: "object" }
  #     - { label: "Matériau", name: "material", widget: "string" }
  #     - { label: "Couleur", name: "color", widget: "string" }
  #     - { label: "Stock", name: "stock", widget: "number" }
